apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:OPaT2eAuHrMG7VD0eGuYIaaCCsMoDU65mu1X4WeCT+JCIuCkRnEWPbIFDOX1Rmolb4jfjdd/VyaWClNs7T5m6poV8khHJRRrxkII/y415T5CiXCe0V9TqUkun99C+trBvrcQX1ew+fRysH1+A4wYmppvB2Ok2wR+chYyeIOnEOKluGvsVJ3WqY8+SrQCXtsb3rLWKr7V8PKBmzPhoDNb1QoLDRMZGL1k6brOaQzgiij0ABbEtc0jjP8MCNsNfndXt9PMOvFwoPSv3q4v4c4856I1UWCR0vXb,iv:Ltt4FH+g9aQ1uHHqLwFGeeChn+8JNjQjAd/UJsdyxYs=,tag:vzqQlgA6VP4oQjA7rmX8gw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2qytgdyda4hx70zth2e973njacf79sqpqvqeax4l4zlchvdlvtqg5pqxy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTXk4MCsxWFlLeFg1bjFJ
            NzV3Z3pwSjErbFd2bDcyZ3Jvekg4VGN2bkM4Ck5kdUxTZEd6a2svb0V2SUZ0d0Nm
            YWhmTStiWkc4RzFORmZZRytoNklnc00KLS0tIFcxR0diZU5XaWZZZ2hvcU53RXIz
            eGtCM0tCMC9OWHFidEg1dXZJRjB1MncK3rL8Ji16eQoPIpcj6L4z4EcyCO9KaPia
            XWNx2SvGRC0yOsHbtV4bRn4mrYEwnCuSS41dnjyo3wyNOEhgpFMI/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-10T21:39:20Z"
    mac: ENC[AES256_GCM,data:AYU7ePqMr+f4ba4VlqnXOf9rZPSQogKI2SQY6Rjn59BOfwIHFTe3PsTWFSr2E2bmBnD11ebZQ/lBItTgbhjAQsL8NiUg0VpD3C/CnxaraPscCiKDAKVRw1M+HfwHtIJwuJecC2h87OqmAa+2k9XDmklp0n1Jg42Am7GME6nCibc=,iv:/cbyWskR9udyvY2ei8WTdJJ2olhK9FU+txWjvLlf4UU=,tag:Uvb3U9xfYiKMz6CAD/w0rA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
