apiVersion: v1
data:
    username: ENC[AES256_GCM,data:ks0To0gYV3Y=,iv:cn6wP6Y2CUvZIOGPM2EFTUE5bV1/IM3jcbXK92c2u24=,tag:kvkCP4oI6wZPymb8RRJcPg==,type:str]
    password: ENC[AES256_GCM,data:ITMZRZxrQmZp,iv:5fpCHZiUlPrQiNYazwq963DQIDAwdwiwucCJB8VMRQI=,tag:tv5SR1AcO1xokIoRAdU0xQ==,type:str]
kind: Secret
metadata:
    name: wallabag-db-creds
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2qytgdyda4hx70zth2e973njacf79sqpqvqeax4l4zlchvdlvtqg5pqxy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyU29McEsvTUdnMXdEWFlw
            c2NqcWZnTGRMb1F6ZFhHa1BSTUhPQTBkZTEwCnpQRE9jeVZVaDlqc3pyZnBiN3VJ
            V1NDK3ltYTAvcmZRUFQ3dW8zVXZMelEKLS0tIEZvcG5SakZtcTNpeC9aTyt0YXdK
            TGszQ2VRRllOdzdwL293d1piOFJBeHMKAmUDPAWjvlxP3L/QDXAUOp5Q8HmsHc16
            0gEN0Pi2yfSFsUNVoXEhUpEdN7bFdPDUwWswLzBwEnaI1d/RuInK+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T21:39:18Z"
    mac: ENC[AES256_GCM,data:KXYdGgEmLyHarfFVyVli53LnAM4rcxfEIoLyuMIRJQlpXz8XTrvSVek+rTH1Wg0jy7wKM7U4EJtlzA9teisKf2vmoIkJdn0r1GkmSyTtwpS31A1tM8HLcIn5W5Yp4ZyaM7+Ww0cf5sUhZ/CQcw0QgIWOGhH0SZ+tpqPM+iu1TvE=,iv:8yyGCgxKWBgY4TKr7284/r6smA+iVYur4bB76LfWAoM=,tag:kU+6DDaO0eJEi/GK9I3NpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
