apiVersion: v1
data:
    username: ENC[AES256_GCM,data:Z9A6DFCED1OrKqqb,iv:zZzkFuNBbk810MttPMUvwu2qvu1m3qW0Slx+ZhYAyjA=,tag:/hq2MwKEUGOTBuTM0+S2qQ==,type:str]
    password: ENC[AES256_GCM,data:f2k95XX6YXhZb79yFOpyUA==,iv:gk9Q8XJqQM98OtCqw8jYSVEw7+zDRnqj4407IzqKgiA=,tag:cTH6L+S/HUjZBixDt/5DeA==,type:str]
kind: Secret
metadata:
    name: wallabag-db-creds
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v2qytgdyda4hx70zth2e973njacf79sqpqvqeax4l4zlchvdlvtqg5pqxy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVGpRVjAxZjdmVHNLSTd3
            cXo4RDlaNGE4U1hMTFBDWmlRc3g5UWZvQkE4ClpRa2xuQVVCemlYQlYzU2k3RlFH
            VVNBZzhXcFVFUmJXZi9xN3hreTVDODAKLS0tIEpGMmJrcjFoWERXOStkNmpCbC9z
            dndvUmFPbWxWbVZJN1BUNnMwOEhGNGMKCSlFKJoy6n7Oca6CC5wjnV4BVHKzhwnn
            7Xkvt7mNAs8/WN7DhXvIzYEPNMnY3EDXcv0YAYF5nQMtdgWAo1wuJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T21:47:18Z"
    mac: ENC[AES256_GCM,data:7LE60BAZ99iYvNWnSjQZf1+ICHjgGqSJZ7z0w1ijCCnzX0my+9S65CJ7hrXxZGdRYslmmXwesW+tSgwbrhCB+/ZaEAUn5Tv1lHUh3sNWL2/PnNFPwdu82qCtlOKok6s//9AyHYv7EEojBwuDCG+bfmmnDnXtDz9Ig2HyGoO46bA=,iv:FvQq74Jz7Gm6mZun7C3AAtCj6RZJ/KW4C4pPnUYsYQA=,tag:+6Q0dCXh+Ji2JWxuxBHltg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
